
package ru.gosuslugi.dom.schema.integration.uk_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Асинхронный сервис Управление контентом
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UkAsyncService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk-service-async/", wsdlLocation = "file:/C:/Progs/GisExchanger/wsdl/hcs_wsdl_xsd_v.12.2.0.18/uk/hcs-uk-service-async.wsdl")
public class UkAsyncService
    extends Service
{

    private final static URL UKASYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException UKASYNCSERVICE_EXCEPTION;
    private final static QName UKASYNCSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/uk-service-async/", "UkAsyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Progs/GisExchanger/wsdl/hcs_wsdl_xsd_v.12.2.0.18/uk/hcs-uk-service-async.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UKASYNCSERVICE_WSDL_LOCATION = url;
        UKASYNCSERVICE_EXCEPTION = e;
    }

    public UkAsyncService() {
        super(__getWsdlLocation(), UKASYNCSERVICE_QNAME);
    }

    public UkAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UKASYNCSERVICE_QNAME, features);
    }

    public UkAsyncService(URL wsdlLocation) {
        super(wsdlLocation, UKASYNCSERVICE_QNAME);
    }

    public UkAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UKASYNCSERVICE_QNAME, features);
    }

    public UkAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UkAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UkAsyncPort
     */
    @WebEndpoint(name = "UkAsyncPort")
    public UkAsyncPort getUkAsyncPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/uk-service-async/", "UkAsyncPort"), UkAsyncPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UkAsyncPort
     */
    @WebEndpoint(name = "UkAsyncPort")
    public UkAsyncPort getUkAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/uk-service-async/", "UkAsyncPort"), UkAsyncPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UKASYNCSERVICE_EXCEPTION!= null) {
            throw UKASYNCSERVICE_EXCEPTION;
        }
        return UKASYNCSERVICE_WSDL_LOCATION;
    }

}
