
package ru.gosuslugi.dom.schema.integration.organizations_registry_common_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDataProviderRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDataProviderResult;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDelegatedAccessResult;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportObjectsDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportObjectsDelegatedAccessResult;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportOrgRegistryRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportOrgRegistryResult;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportTerritoryDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportTerritoryDelegatedAccessResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegOrgPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.organizations_registry_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RegOrgPortsType {


    /**
     * экспорт сведений об организациях
     * 
     * @param exportOrgRegistryRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportOrgRegistryResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrgRegistry")
    @WebResult(name = "exportOrgRegistryResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportOrgRegistryResult")
    public ExportOrgRegistryResult exportOrgRegistry(
        @WebParam(name = "exportOrgRegistryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportOrgRegistryRequest")
        ExportOrgRegistryRequest exportOrgRegistryRequest)
        throws Fault
    ;

    /**
     * экспорт сведений о поставщиках данных
     * 
     * @param exportDataProviderRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDataProviderResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProvider")
    @WebResult(name = "exportDataProviderResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDataProviderResult")
    public ExportDataProviderResult exportDataProvider(
        @WebParam(name = "exportDataProviderRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDataProviderRequest")
        ExportDataProviderRequest exportDataProviderRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений о делегированных правах
     * 
     * @param exportDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDelegatedAccessResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDelegatedAccess")
    @WebResult(name = "exportDelegatedAccessResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDelegatedAccessResult")
    public ExportDelegatedAccessResult exportDelegatedAccess(
        @WebParam(name = "exportDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDelegatedAccessRequest")
        ExportDelegatedAccessRequest exportDelegatedAccessRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений об объектах из заявок на делегирование прав
     * 
     * @param exportObjectsDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportObjectsDelegatedAccessResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportObjectsDelegatedAccess")
    @WebResult(name = "exportObjectsDelegatedAccessResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportObjectsDelegatedAccessResult")
    public ExportObjectsDelegatedAccessResult exportObjectsDelegatedAccess(
        @WebParam(name = "exportObjectsDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportObjectsDelegatedAccessRequest")
        ExportObjectsDelegatedAccessRequest exportObjectsDelegatedAccessRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений о территориях из заявок на делегирование прав
     * 
     * @param exportTerritoryDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportTerritoryDelegatedAccessResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportTerritoryDelegatedAccess")
    @WebResult(name = "exportTerritoryDelegatedAccessResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportTerritoryDelegatedAccessResult")
    public ExportTerritoryDelegatedAccessResult exportTerritoryDelegatedAccess(
        @WebParam(name = "exportTerritoryDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportTerritoryDelegatedAccessRequest")
        ExportTerritoryDelegatedAccessRequest exportTerritoryDelegatedAccessRequest)
        throws Fault
    ;

}
