
package ru.gosuslugi.dom.schema.integration.nsi_common_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiItemRequest;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiItemResult;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiListRequest;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiListResult;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiPagingItemRequest;
import ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiPagingItemResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsType {


    /**
     * ВИ_НСИ_ППС. Получить перечень общесистемных справочников с указанием даты последнего изменения каждого из них.
     * 
     * @param exportNsiListRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiListResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiList")
    @WebResult(name = "exportNsiListResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiListResult")
    public ExportNsiListResult exportNsiList(
        @WebParam(name = "exportNsiListRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiListRequest")
        ExportNsiListRequest exportNsiListRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ПДС. Получить данные общесистемного справочника.
     * 
     * @param exportNsiItemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiItemResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiItem")
    @WebResult(name = "exportNsiItemResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiItemResult")
    public ExportNsiItemResult exportNsiItem(
        @WebParam(name = "exportNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiItemRequest")
        ExportNsiItemRequest exportNsiItemRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ПДС_ПОСТР. Получить данные общесистемного справочника.
     * 
     * @param exportNsiPagingItemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.nsi_common.ExportNsiPagingItemResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportNsiPagingItem")
    @WebResult(name = "exportNsiPagingItemResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiPagingItemResult")
    public ExportNsiPagingItemResult exportNsiPagingItem(
        @WebParam(name = "exportNsiPagingItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common/", partName = "exportNsiPagingItemRequest")
        ExportNsiPagingItemRequest exportNsiPagingItemRequest)
        throws Fault
    ;

}
