
package ru.gosuslugi.dom.schema.integration.rap_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.ImportResult;
import ru.gosuslugi.dom.schema.integration.rap.ExportDecreesAndDocumentsRequest;
import ru.gosuslugi.dom.schema.integration.rap.ExportDecreesAndDocumentsResult;
import ru.gosuslugi.dom.schema.integration.rap.ImportDecreesAndDocumentsRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RapPort", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.rap.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.individual_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RapPort {


    /**
     * Импорт постановлений и процессуальных документов
     * 
     * @param importDecreesAndDocumentsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importDecreesAndDocumentsData")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "ImportDecreesAndDocumentsResult")
    public ImportResult importDecreesAndDocumentsData(
        @WebParam(name = "ImportDecreesAndDocumentsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "ImportDecreesAndDocumentsRequest")
        ImportDecreesAndDocumentsRequest importDecreesAndDocumentsRequest)
        throws Fault
    ;

    /**
     * Экспорт постановлений и процессуальных документов
     * 
     * @param exportDecreesAndDocumentsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.rap.ExportDecreesAndDocumentsResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDecreesAndDocumentsData")
    @WebResult(name = "ExportDecreesAndDocumentsResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "ExportDecreesAndDocumentsResult")
    public ExportDecreesAndDocumentsResult exportDecreesAndDocumentsData(
        @WebParam(name = "ExportDecreesAndDocumentsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "ExportDecreesAndDocumentsRequest")
        ExportDecreesAndDocumentsRequest exportDecreesAndDocumentsRequest)
        throws Fault
    ;

}
