
package ru.gosuslugi.dom.schema.integration.nsi_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ExportDataProviderNsiItemRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ExportDataProviderNsiPagingItemRequest;
import ru.gosuslugi.dom.schema.integration.nsi.GetStateResult;
import ru.gosuslugi.dom.schema.integration.nsi.ImportAdditionalServicesRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportBaseDecisionMSPRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportCapitalRepairWorkRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportCommunalInfrastructureSystemRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportGeneralNeedsMunicipalResourceRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportMunicipalServicesRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportOrganizationWorksRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsTypeAsync {


    /**
     * ВИ_НСИ_ИДС_1. Импортировать данные справочника 1 "Дополнительные услуги".
     * 
     * @param importAdditionalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importAdditionalServices")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importAdditionalServicesResult")
    public AckRequest importAdditionalServices(
        @WebParam(name = "importAdditionalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importAdditionalServicesRequest")
        ImportAdditionalServicesRequest importAdditionalServicesRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_51. Импортировать данные справочника 51 "Коммунальные услуги".
     * 
     * @param importMunicipalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalServices")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importMunicipalServicesResult")
    public AckRequest importMunicipalServices(
        @WebParam(name = "importMunicipalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importMunicipalServicesRequest")
        ImportMunicipalServicesRequest importMunicipalServicesRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_59. Импортировать данные справочника 59 "Работы и услуги организации".
     * 
     * @param importOrganizationWorksRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationWorks")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importOrganizationWorksResult")
    public AckRequest importOrganizationWorks(
        @WebParam(name = "importOrganizationWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importOrganizationWorksRequest")
        ImportOrganizationWorksRequest importOrganizationWorksRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_272. Импортировать данные справочника 272 "Система коммунальной инфраструктуры".
     * 
     * @param importCommunalInfrastructureSystemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importCommunalInfrastructureSystem")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importCommunalInfrastructureRequest")
    public AckRequest importCommunalInfrastructureSystem(
        @WebParam(name = "importCommunalInfrastructureSystemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importCommunalInfrastructureSystemRequest")
        ImportCommunalInfrastructureSystemRequest importCommunalInfrastructureSystemRequest)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.nsi.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * Экспортировать данные справочников поставщика информации 
     * 
     * @param exportDataProviderNsiItemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProviderNsiItem")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDataProviderNsiItem(
        @WebParam(name = "exportDataProviderNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "exportDataProviderNsiItemRequest")
        ExportDataProviderNsiItemRequest exportDataProviderNsiItemRequest)
        throws Fault
    ;

    /**
     * Экспортировать данные справочников поставщика информации постранично 
     * 
     * @param exportDataProviderNsiPagingItemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProviderPagingNsiItem")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDataProviderPagingNsiItem(
        @WebParam(name = "exportDataProviderNsiPagingItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "exportDataProviderNsiPagingItemRequest")
        ExportDataProviderNsiPagingItemRequest exportDataProviderNsiPagingItemRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_219. Импортировать данные справочника 219 "Вид работ капитального ремонта".
     * 
     * @param importCapitalRepairWorkRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importCapitalRepairWork")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importCapitalRepairWorkResult")
    public AckRequest importCapitalRepairWork(
        @WebParam(name = "importCapitalRepairWorkRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importCapitalRepairWorkRequest")
        ImportCapitalRepairWorkRequest importCapitalRepairWorkRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_302. Импортировать данные справочника 302 "Основание принятия решения о мерах социальной поддержки гражданина"
     * 
     * @param importBaseDecisionMSPRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importBaseDecisionMSP")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importBaseDecisionMSPResult")
    public AckRequest importBaseDecisionMSP(
        @WebParam(name = "importBaseDecisionMSPRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importBaseDecisionMSPRequest")
        ImportBaseDecisionMSPRequest importBaseDecisionMSPRequest)
        throws Fault
    ;

    /**
     * Импортировать данные справочника 337 "Коммунальные ресурсы, потребляемые при использовании и содержании общего имущества в многоквартирном доме"
     * 
     * @param importGeneralNeedsMunicipalResourceRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importGeneralNeedsMunicipalResource")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importGeneralNeedsMunicipalResourceResult")
    public AckRequest importGeneralNeedsMunicipalResource(
        @WebParam(name = "importGeneralNeedsMunicipalResourceRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importGeneralNeedsMunicipalResourceRequest")
        ImportGeneralNeedsMunicipalResourceRequest importGeneralNeedsMunicipalResourceRequest)
        throws Fault
    ;

}
