
package ru.gosuslugi.dom.schema.integration.volume_quality_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Сервис управления сведениями об объеме и качестве коммунальных услуг и коммунальных ресурсов (асинхронный)
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VolumeQualityServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/volume-quality-service-async/", wsdlLocation = "file:/C:/Progs/GisExchanger/wsdl/hcs_wsdl_xsd_v.12.2.0.18/volume-quality/hcs-volume-quality-service-async.wsdl")
public class VolumeQualityServiceAsync
    extends Service
{

    private final static URL VOLUMEQUALITYSERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException VOLUMEQUALITYSERVICEASYNC_EXCEPTION;
    private final static QName VOLUMEQUALITYSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service-async/", "VolumeQualityServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Progs/GisExchanger/wsdl/hcs_wsdl_xsd_v.12.2.0.18/volume-quality/hcs-volume-quality-service-async.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOLUMEQUALITYSERVICEASYNC_WSDL_LOCATION = url;
        VOLUMEQUALITYSERVICEASYNC_EXCEPTION = e;
    }

    public VolumeQualityServiceAsync() {
        super(__getWsdlLocation(), VOLUMEQUALITYSERVICEASYNC_QNAME);
    }

    public VolumeQualityServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOLUMEQUALITYSERVICEASYNC_QNAME, features);
    }

    public VolumeQualityServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, VOLUMEQUALITYSERVICEASYNC_QNAME);
    }

    public VolumeQualityServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOLUMEQUALITYSERVICEASYNC_QNAME, features);
    }

    public VolumeQualityServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VolumeQualityServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VolumeQualityPortAsync
     */
    @WebEndpoint(name = "VolumeQualityPortAsync")
    public VolumeQualityPortAsync getVolumeQualityPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service-async/", "VolumeQualityPortAsync"), VolumeQualityPortAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VolumeQualityPortAsync
     */
    @WebEndpoint(name = "VolumeQualityPortAsync")
    public VolumeQualityPortAsync getVolumeQualityPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service-async/", "VolumeQualityPortAsync"), VolumeQualityPortAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOLUMEQUALITYSERVICEASYNC_EXCEPTION!= null) {
            throw VOLUMEQUALITYSERVICEASYNC_EXCEPTION;
        }
        return VOLUMEQUALITYSERVICEASYNC_WSDL_LOCATION;
    }

}
