
package ru.gosuslugi.dom.schema.integration.organizations_registry_common_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDataProviderRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportObjectsDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportOrgRegistryRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.ExportTerritoryDelegatedAccessRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry_common.GetStateResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegOrgPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.organizations_registry_common.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RegOrgPortsTypeAsync {


    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.organizations_registry_common.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * 
     * @param exportOrgRegistryRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrgRegistry")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportOrgRegistry(
        @WebParam(name = "exportOrgRegistryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportOrgRegistryRequest")
        ExportOrgRegistryRequest exportOrgRegistryRequest)
        throws Fault
    ;

    /**
     * экспорт сведений о поставщиках данных
     * 
     * @param exportDataProviderRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProvider")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDataProvider(
        @WebParam(name = "exportDataProviderRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDataProviderRequest")
        ExportDataProviderRequest exportDataProviderRequest)
        throws Fault
    ;

    /**
     * 
     * @param exportDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDelegatedAccess")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDelegatedAccess(
        @WebParam(name = "exportDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportDelegatedAccessRequest")
        ExportDelegatedAccessRequest exportDelegatedAccessRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений об объектах из заявок на делегирование прав
     * 
     * @param exportObjectsDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportObjectsDelegatedAccess")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportObjectsDelegatedAccess(
        @WebParam(name = "exportObjectsDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportObjectsDelegatedAccessRequest")
        ExportObjectsDelegatedAccessRequest exportObjectsDelegatedAccessRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений о территориях из заявок на делегирование прав
     * 
     * @param exportTerritoryDelegatedAccessRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportTerritoryDelegatedAccess")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportTerritoryDelegatedAccess(
        @WebParam(name = "exportTerritoryDelegatedAccessRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common/", partName = "exportTerritoryDelegatedAccessRequest")
        ExportTerritoryDelegatedAccessRequest exportTerritoryDelegatedAccessRequest)
        throws Fault
    ;

}
