
package ru.gosuslugi.dom.schema.integration.volume_quality_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Сервис управления сведениями об объеме и качестве коммунальных услуг и коммунальных ресурсов (синхронный)
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VolumeQualityService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/volume-quality-service/", wsdlLocation = "file:/C:/Progs/Soap2Gis/wsdl/hcs_wsdl_xsd_v.11.13.0.11/volume-quality/hcs-volume-quality-service.wsdl")
public class VolumeQualityService
    extends Service
{

    private final static URL VOLUMEQUALITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException VOLUMEQUALITYSERVICE_EXCEPTION;
    private final static QName VOLUMEQUALITYSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service/", "VolumeQualityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Progs/Soap2Gis/wsdl/hcs_wsdl_xsd_v.11.13.0.11/volume-quality/hcs-volume-quality-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOLUMEQUALITYSERVICE_WSDL_LOCATION = url;
        VOLUMEQUALITYSERVICE_EXCEPTION = e;
    }

    public VolumeQualityService() {
        super(__getWsdlLocation(), VOLUMEQUALITYSERVICE_QNAME);
    }

    public VolumeQualityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOLUMEQUALITYSERVICE_QNAME, features);
    }

    public VolumeQualityService(URL wsdlLocation) {
        super(wsdlLocation, VOLUMEQUALITYSERVICE_QNAME);
    }

    public VolumeQualityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOLUMEQUALITYSERVICE_QNAME, features);
    }

    public VolumeQualityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VolumeQualityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VolumeQualityPort
     */
    @WebEndpoint(name = "VolumeQualityPort")
    public VolumeQualityPort getVolumeQualityPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service/", "VolumeQualityPort"), VolumeQualityPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VolumeQualityPort
     */
    @WebEndpoint(name = "VolumeQualityPort")
    public VolumeQualityPort getVolumeQualityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/volume-quality-service/", "VolumeQualityPort"), VolumeQualityPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOLUMEQUALITYSERVICE_EXCEPTION!= null) {
            throw VOLUMEQUALITYSERVICE_EXCEPTION;
        }
        return VOLUMEQUALITYSERVICE_WSDL_LOCATION;
    }

}
