
package ru.gosuslugi.dom.schema.integration.tariff_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportTariffDifferentiationRequest;
import ru.gosuslugi.dom.schema.integration.tariff.GetStateResult;
import ru.gosuslugi.dom.schema.integration.tariff.ImportResidentialPremisesUsageRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ImportSocialNormsRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TariffAsyncPort", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.tariff.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface TariffAsyncPort {


    /**
     * Результат обработки асинхронного вызова
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.tariff.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * Импорт информации о социальных нормах потребления электрической энергии
     * 
     * @param importSocialNormsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importSocialNorms")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importSocialNormsResult")
    public AckRequest importSocialNorms(
        @WebParam(name = "importSocialNormsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importSocialNormsRequest")
        ImportSocialNormsRequest importSocialNormsRequest)
        throws Fault
    ;

    /**
     * Импорт информации о размерах платы за пользование жилым помещением
     * 
     * @param importResidentialPremisesUsageRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importResidentialPremisesUsage")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importResidentialPremisesUsageResult")
    public AckRequest importResidentialPremisesUsage(
        @WebParam(name = "importResidentialPremisesUsageRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importResidentialPremisesUsageRequest")
        ImportResidentialPremisesUsageRequest importResidentialPremisesUsageRequest)
        throws Fault
    ;

    /**
     * Экспорт списка критериев дифференциации
     * 
     * @param exportTariffDifferentiationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportTariffDifferentiation")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportTariffDifferentiationResult")
    public AckRequest exportTariffDifferentiation(
        @WebParam(name = "exportTariffDifferentiationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportTariffDifferentiationRequest")
        ExportTariffDifferentiationRequest exportTariffDifferentiationRequest)
        throws Fault
    ;

}
