
package ru.gosuslugi.dom.schema.integration.uk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.ImportResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UkPort", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.uk.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface UkPort {


    /**
     * Импорт документов закона/нормативно-правового акта регионального уровня
     * 
     * @param importDocumentRegionRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importDocumentRegion")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importDocumentRegionResult")
    public ImportResult importDocumentsRegion(
        @WebParam(name = "importDocumentRegionRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/", partName = "importDocumentRegionRequest")
        ImportDocumentRegionRequest importDocumentRegionRequest)
        throws Fault
    ;

    /**
     * Импорт документов закона/нормативно-правового акта уровня муниципальных образований
     * 
     * @param importDocumentMunicipalRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importDocumentMunicipal")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importDocumentMunicipalResult")
    public ImportResult importDocumentsMunicipal(
        @WebParam(name = "importDocumentMunicipalRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/", partName = "importDocumentMunicipalRequest")
        ImportDocumentMunicipalRequest importDocumentMunicipalRequest)
        throws Fault
    ;

    /**
     * Экспорт документов
     * 
     * @param exportDocumentRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.uk.ExportDocumentResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDocument")
    @WebResult(name = "exportDocumentResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/", partName = "exportDocumentResult")
    public ExportDocumentResult exportDocuments(
        @WebParam(name = "exportDocumentRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/", partName = "exportDocumentRequest")
        ExportDocumentRequest exportDocumentRequest)
        throws Fault
    ;

}
