
package ru.gosuslugi.dom.schema.integration.uk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Сервис Управление контентом
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UkService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/uk/", wsdlLocation = "file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.7.0.10.1/hcs_wsdl_xsd_v.11.7.0.10/uk/hcs-uk-service.wsdl")
public class UkService
    extends Service
{

    private final static URL UKSERVICE_WSDL_LOCATION;
    private final static WebServiceException UKSERVICE_EXCEPTION;
    private final static QName UKSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/uk/", "UkService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.7.0.10.1/hcs_wsdl_xsd_v.11.7.0.10/uk/hcs-uk-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UKSERVICE_WSDL_LOCATION = url;
        UKSERVICE_EXCEPTION = e;
    }

    public UkService() {
        super(__getWsdlLocation(), UKSERVICE_QNAME);
    }

    public UkService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UKSERVICE_QNAME, features);
    }

    public UkService(URL wsdlLocation) {
        super(wsdlLocation, UKSERVICE_QNAME);
    }

    public UkService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UKSERVICE_QNAME, features);
    }

    public UkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UkService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UkPort
     */
    @WebEndpoint(name = "UkPort")
    public UkPort getUkPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/uk/", "UkPort"), UkPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UkPort
     */
    @WebEndpoint(name = "UkPort")
    public UkPort getUkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/uk/", "UkPort"), UkPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UKSERVICE_EXCEPTION!= null) {
            throw UKSERVICE_EXCEPTION;
        }
        return UKSERVICE_WSDL_LOCATION;
    }

}
